# Site settings
title: Sarah Maddox Groves
email: sarahmaddoxgroves@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm currently a Ph.D. Candidate at Vanderbilt University.
  I'm a cancer systems biologist studying phenotypic transitions in Small Cell
  Lung Cancer, but I'm also interested in single cell analysis, machine learning,
  and data analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "smgroves.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sarahmgroves
github_username:  smgroves
instagram_username: sarahmaddox4

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
